name: Workflow CI/CD

# Control when the action will run

on:
  push: 
     branches: 
        - main
  
  # Allow you to run this workflow manualy from the actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build ⛏
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main  
  Dev:
    runs-on: ubuntu-latest
    environment: Dev
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: Sync files to hosting
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ftp.mosframtech.com
          username: trackerapp@tracker.mosframtech.com
          password: trackerapp@2023
          local-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            public
            src
