name: Workflow CI/CD

# Control when the action will run

on:
  push: 
     branches: 
        - main
  
  # Allow you to run this workflow manualy from the actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build ⛏
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main  
  Dev:
    runs-on: ubuntu-latest
    environment: Dev
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2 
        
      - name: 🚚 Install Composer Dependencies SITE
        working-directory: ./
        run: composer install --prefer-dist
    
      - name: 🚚 Install Composer Dependencies ADM
        working-directory: ./public/adm
        run: composer install --prefer-dist
        
      - name: Sync files to hosting
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: mosframtech.com
          username: trackerapp@tracker.mosframtech.com
          password: trackerapp@2023
          local-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            public
            src
